version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    ignore:
      # minimal maven version is fixed
      - dependency-name: org.apache.maven:maven-plugin-api
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
